### ISSUE TITLE
[interface] API does not exposes DHCP bind information

### ISSUE THREAD

**Issue by ronanjs** [Spirent/openperf#401]
Configure Open with such an interface 
```
  /interfaces/dataplane3:
    port_id: ens4f3
    config:
      protocols:
        - eth:
            mac_address: "00:10:94:01:1a:2c"
        - ipv4:
            method: dhcp
            dhcp:
             - hostname: "bingo"
```

There is no way to know what is the DHCP client status (failed or success), not what is the bounded IP address in case ofsucces
